version: "3"
services:
  backend:
    container_name: portfolio_backend
    build: ./backend
    command: gunicorn --config ./gunicorn_config.py wsgi:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
