version: "3"
services:
  backend:
    container_name: portfolio_backend
    build: ./backend
    command: gunicorn --config ./gunicorn_config.py wsgi:app
    ports:
      - "5000:5000"
  frontend:
    container_name: portfolio_frontend
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
